server:
  port: 8087
spring:
  application:
    name: order-service
  cloud:
    nacos:
      server-addr: 192.168.106.103:8850
      discovery:
        username: nacos
        password: nacos
        namespace: 2ce3b450-5f08-4fae-a38d-c7da174ddd15
    # 排除spring-cloud内置ribbon
    loadbalancer:
      ribbon:
        enabled: false